spring:
  application:
    name: k8s-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: Keat6951
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect